name: Tag Release

on:
  push:
    branches:
      - main

jobs:
    release-tag:
        runs-on: ubuntu-latest
        if: ${{ github.ref == 'refs/heads/main' && github.event_name == 'push' }}
        name: 'Create Release Tag'
        outputs:
            RELEASE_TAG: ${{ steps.tag_version.outputs.new_tag }}
        steps:
            - uses: actions/checkout@v4
            - name: Release Tag
              id: tag_version
              uses: mathieudutour/github-tag-action@v6.2
              with:
                github_token: ${{ secrets.GITHUB_TOKEN }}
                tag_prefix: ''

    create-release:
        name: 'Create Release'
        runs-on: ubuntu-latest
        needs: ['release-tag']
        steps:
            - name: 'Checkout'
              uses: 'actions/checkout@v4'

            - name: Create a GitHub release
              uses: ncipollo/release-action@v1
              with:
                tag: ${{ needs.release-tag.outputs.RELEASE_TAG }}
                name: Release ${{ needs.release-tag.outputs.RELEASE_TAG }}
                body: ${{ needs.release-tag.outputs.RELEASE_TAG }}